workflows:
  ios-testflight:
    name: Build & Publish iOS to TestFlight
    max_build_duration: 60
    environment:
      # pick the Flutter channel you use; "stable" is a good default
      flutter: stable
      xcode: latest
      # ensure CocoaPods is available
      cocoapods: default
      vars:
        # these are injected from Codemagic UI (Environment variables or Secrets)
        APP_ID:               $APP_ID             # e.g. com.example.covoisino
        APP_STORE_CONNECT_KEY: $APP_STORE_CONNECT_KEY  # the contents of your .p8 API key (or path)
        KEY_ID:               $KEY_ID             # “2ABCD3EFGH”
        ISSUER_ID:            $ISSUER_ID          # “12345678‑90ab‑cdef‑1234‑567890abcdef”
        # optional: override Flutter build mode
        FLUTTER_BUILD_MODE:   release
    triggers:
      - push                 # build on every Git push
    scripts:
      - name: Get Dart dependencies
        script: |
          flutter pub get

      - name: Install iOS pods
        script: |
          # make sure your Podfile is checked in under ios/Podfile
          cd ios
          pod repo update     # (optional, to refresh spec repos)
          pod install --verbose
          cd ..

      - name: Build IPA
        script: |
          # using Flutter’s ipa builder makes codesign easier
          flutter build ipa \
            --export-options-plist=ios/ExportOptions.plist \
            --${FLUTTER_BUILD_MODE}

    artifacts:
      - build/ios/ipa/*.ipa  # grab the generated IPA for upload

    publishing:
      testflight:
        app_id: $APP_ID
        api_key: 
          key_id: $KEY_ID
          issuer_id: $ISSUER_ID
          key_content: $APP_STORE_CONNECT_KEY