// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDqeU-n9EMlv_klrpO5RZPtGIztRwhbv8',
    appId: '1:333501090169:web:eaafeac2f46532f35487a8',
    messagingSenderId: '333501090169',
    projectId: 'covoisino-3dd5d',
    authDomain: 'covoisino-3dd5d.firebaseapp.com',
    storageBucket: 'covoisino-3dd5d.firebasestorage.app',
    measurementId: 'G-DV25M9344J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLlcTIt35iWDttGPxB_lQULoU7PAhmhRA',
    appId: '1:333501090169:android:f435bbfec0f1dd3e5487a8',
    messagingSenderId: '333501090169',
    projectId: 'covoisino-3dd5d',
    storageBucket: 'covoisino-3dd5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHwy1wCeGICE6VFI_aAN00ZvtPWbfzfOc',
    appId: '1:333501090169:ios:a990fa1bdbae952f5487a8',
    messagingSenderId: '333501090169',
    projectId: 'covoisino-3dd5d',
    storageBucket: 'covoisino-3dd5d.firebasestorage.app',
    iosBundleId: 'com.example.covoisino',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHwy1wCeGICE6VFI_aAN00ZvtPWbfzfOc',
    appId: '1:333501090169:ios:a990fa1bdbae952f5487a8',
    messagingSenderId: '333501090169',
    projectId: 'covoisino-3dd5d',
    storageBucket: 'covoisino-3dd5d.firebasestorage.app',
    iosBundleId: 'com.example.covoisino',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDqeU-n9EMlv_klrpO5RZPtGIztRwhbv8',
    appId: '1:333501090169:web:db4d1906801100c55487a8',
    messagingSenderId: '333501090169',
    projectId: 'covoisino-3dd5d',
    authDomain: 'covoisino-3dd5d.firebaseapp.com',
    storageBucket: 'covoisino-3dd5d.firebasestorage.app',
    measurementId: 'G-GTBCGE32NX',
  );
}
