# ios/Podfile

platform :ios, '13.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug'   => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Instead of defining flutter_root via Generated.xcconfig,
# just use the FLUTTER_ROOT env var that flutter sets.
flutter_root = ENV['FLUTTER_ROOT']
if flutter_root.nil? || flutter_root.empty?
  raise "FLUTTER_ROOT must be set. Did you install Flutter?"
end

# Pull in the Flutter CocoaPods helper from the SDK
require File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper')

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  # Sets up ARCHS, bitcode, etc.
  flutter_ios_podfile_setup

  # Install all of your Flutter plugins
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # If you run into bitcode errors, uncomment this:
      # config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end